In [3]:
import pandas as pd

gaz = pd.read_csv("../data/2026_Gaz_place_national.txt", sep="|", dtype={"GEOID": str})
gaz.columns = gaz.columns.str.strip()
gaz[["USPS", "NAME", "INTPTLAT", "INTPTLONG"]].head()

  USPS             NAME   INTPTLAT  INTPTLONG
0   AL       Abanda CDP  33.091627 -85.527029
1   AL   Abbeville city  31.565164 -85.259165
2   AL  Adamsville city  33.602593 -86.971705
3   AL     Addison town  34.202681 -87.178004
4   AL       Akron town  32.879393 -87.740644

In [ ]:
gaz["NAME"].str.split().str[-1].value_counts().head(15)

NAME
CDP             12557
city            10239
town             4317
village          3716
borough          1215
comunidad         214
urbana             78
(balance)           8
municipality        7
government          5
County              3
county              1
City                1
Princeton           1
corporation         1
Name: count, dtype: int64

In [16]:
gaz["NAME"].str.split().str[:-1].str.join(', ').str.replace(',', '')

0              Abanda
1           Abbeville
2          Adamsville
3             Addison
4               Akron
             ...
32358       Voladoras
32359    Yabucoa zona
32360      Yauco zona
32361          Yaurel
32362         Yeguada
Name: NAME, Length: 32363, dtype: object

In [17]:
import re

SUFFIXES = [
    " city and borough", "CDP", "city", "town", "village", "borough",
    "comunidad", "urbana", "(balance)", "municipality", "government",
    "County", "county", "City", "Princeton", "corporation",
]

def strip_suffix(name):
    for suffix in sorted(SUFFIXES, key=len, reverse=True):
        if name.endswith(suffix):
            return name[: -len(suffix)]
    return name

REPLACEMENTS = [(r"\bSAINT\b", "ST"), (r"\bFORT\b", "FT"), (r"\bMOUNT\b", "MT")]

def normalize_place_name(name):
    name = name.upper().replace(".", "").replace("'", "").replace("-", " ")
    for pattern, repl in REPLACEMENTS:
        name = re.sub(pattern, repl, name)
    return " ".join(name.split())

In [18]:
gaz["key_city"] = gaz["NAME"].map(strip_suffix).map(normalize_place_name)

In [19]:
gaz.head(20)

,USPS,GEOID,GEOIDFQ,ANSICODE,NAME,LSAD,FUNCSTAT,ALAND,AWATER,ALAND_SQMI,AWATER_SQMI,INTPTLAT,INTPTLONG,key_city
0,AL,0100100,1600000US0100100,2582661,Abanda CDP,57,S,7764032,34284,2.998,0.013,33.091627,-85.527029,ABANDA
1,AL,0100124,1600000US0100124,2403054,Abbeville city,25,A,40255357,107642,15.543,0.042,31.565164,-85.259165,ABBEVILLE
2,AL,0100460,1600000US0100460,2403063,Adamsville city,25,A,67897213,540470,26.215,0.209,33.602593,-86.971705,ADAMSVILLE
3,AL,0100484,1600000US0100484,2405123,Addison town,43,A,9765510,82835,3.770,0.032,34.202681,-87.178004,ADDISON
4,AL,0100676,1600000US0100676,2405125,Akron town,43,A,1776164,13849,0.686,0.005,32.879393,-87.740644,AKRON
5,AL,0100820,1600000US0100820,2403069,Alabaster city,25,A,68148974,820691,26.312,0.317,33.214355,-86.823080,ALABASTER
6,AL,0100988,1600000US0100988,2403074,Albertville city,25,A,69856181,244058,26.972,0.094,34.263130,-86.210660,ALBERTVILLE
7,AL,0101132,1600000US0101132,2403077,Alexander City city,25,A,119270092,751686,46.050,0.290,32.916719,-85.940589,ALEXANDER CITY
8,AL,0101180,1600000US0101180,2402638,Alexandria CDP,57,S,28840486,27589,11.135,0.011,33.760869,-85.872180,ALEXANDRIA
9,AL,0101228,1600000US0101228,2403080,Aliceville city,25,A,11835210,0,4.570,0.000,33.123706,-88.159344,ALICEVILLE
10,AL,0101396,1600000US0101396,2405136,Allgood town,43,A,2831041,1452,1.093,0.001,33.907623,-86.516109,ALLGOOD
11,AL,0101660,1600000US0101660,2405146,Altoona town,43,A,11918557,25442,4.602,0.010,34.040014,-86.305179,ALTOONA
12,AL,0101708,1600000US0101708,2403097,Andalusia city,25,A,51318232,405912,19.814,0.157,31.309436,-86.478031,ANDALUSIA
13,AL,0101756,1600000US0101756,2405149,Anderson town,43,A,3347216,1520,1.292,0.001,34.915675,-87.274274,ANDERSON
14,AL,0101852,1600000US0101852,2403101,Anniston city,25,A,118751123,180468,45.850,0.070,33.673472,-85.810864,ANNISTON
15,AL,0102116,1600000US0102116,2403104,Arab city,25,A,34528140,344543,13.331,0.133,34.332387,-86.501167,ARAB
16,AL,0102260,1600000US0102260,2405163,Ardmore town,43,A,5290518,21212,2.043,0.008,34.987837,-86.829022,ARDMORE
17,AL,0102320,1600000US0102320,2405164,Argo city,25,A,28420758,147613,10.973,0.057,33.697861,-86.505760,ARGO
18,AL,0102428,1600000US0102428,2405166,Ariton town,43,A,13182492,0,5.090,0.000,31.597772,-85.713061,ARITON
19,AL,0102500,1600000US0102500,2405167,Arley town,43,A,10091133,33989,3.896,0.013,34.076234,-87.217831,ARLEY